Added index and appendix to neuroscience
openstax/cookbook pull request #291
Opened 2023-11-06 19:39 UTC by ckline-tryptic

Issue: [5284](https://github.com/openstax/cnx-recipes/issues/5284)

2023-11-15 15:46 UTC, kswanson33 commented
looks like neuroscience spec files could use an update. you can update with
1. run neuroscience test locally with `rspec spec/recipes_spec/main_spec.rb:L#`
2. run `./scripts/update_recipes_spec_data`
3. check that `expected_output` for neuroscience has changed in the expected way

2023-11-16 21:36 UTC, ckline-tryptic commented
Unfortunately, while fixing the expected output, ran into some errors with injected exercises update from main. Will keep an eye on main for the fix, then proceed.

2023-11-30 09:49 UTC, wilkus27 requested changes

2023-11-30 09:49 UTC, wilkus27 commented on CHANGELOG.md
> +* Added `index` and `appendix` to `neuroscience`
Sorry, first I approved but then I noticed problem with CHANGELOG. Please move this log to `Unreleased`. Versions that are already released shouldn't be changed.

2023-11-30 18:21 UTC, kswanson33 approved these changes

2023-12-01 07:23 UTC, wilkus27 approved these changes
Looks good :wink:

2023-12-08 13:15 UTC, wilkus27 commented on lib/recipes/neuroscience/recipe.rb
> +  BakeIndex.v1(book: book)
It's added twice

2023-12-12 16:24 UTC, merged