remove iframe baking from BakeAutotitledNotes
openstax/cookbook pull request #52
Opened 2022-04-05 20:57 UTC by kswanson33

2022-04-12 13:58 UTC, LostMojo commented on CHANGELOG.md
> +* Link to rex from iframe in `BakeIframes`
Are we not adding minor/major/patch to the end of changes now?

2022-04-12 14:24 UTC, LostMojo commented on CHANGELOG.md
> +* Link to rex from iframe in `BakeIframes`
Cool! Thank you for clarifying

2022-04-12 16:03 UTC, ajluk commented on lib/kitchen/element_base.rb
> +        page_string = "#{page.count_in(:chapter) - 1}-"
Can I ask why in the section page case such string was used - `page_in_chapter -1`. I was wondering just out of curiosity why it is always 1and not the numbering we use for sections, like `chapter_number.page_in_chapter_number`.

2022-04-12 16:24 UTC, ajluk commented on spec/kitchen_spec/directions/bake_iframes/v1_spec.rb
> +  let(:book_with_error_prone_iframe) do
I'm not fully understand why in this book case the iframe is proning error :sweat_smile:

2022-04-12 16:28 UTC, ajluk requested changes
@kswanson33 I looked through it all and was concerned about only one place (composite pages title link text) and beside left some comments where I wasn't sure what's going on.

2022-04-12 16:49 UTC, kswanson33 commented on lib/kitchen/element_base.rb
> +      page = element_with_ancestors.ancestor(:page) if element_with_ancestors.has_ancestor?(:page)
we're expecting either a page ancestor or a composite page ancestor to exist. this allows the composite page case to pass through without throwing an error.

2022-04-12 17:34 UTC, kswanson33 commented on spec/kitchen_spec/directions/bake_iframes/v1_spec.rb
> +        "Unable to find rex link for iframe with parent id=\n"
I know this error message isn't very helpful when the error is being caused by no IDs, but I'm not actually expecting this error case to come up very much

2022-04-13 11:39 UTC, ajluk commented on lib/kitchen/element_base.rb
> +      page = element_with_ancestors.ancestor(:page) if element_with_ancestors.has_ancestor?(:page)
Thank you for clarifying! :relaxed:

2022-04-13 11:49 UTC, ajluk approved these changes
Looks really good, thank you for clarifying and adding more error checking test cases Kendra!

2022-04-13 13:27 UTC, merged